### PR TITLE
fix predictions errors

### LINKED ISSUE #5: predictions errors with no categorical predictors
I’m having trouble predicting from a fitted GP. Here’s a simple example: 

``` r
library(GauPro)
#> Loading required package: mixopt
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Loading required package: ggplot2
#> Loading required package: splitfngr
#> Loading required package: numDeriv
#> Loading required package: rmarkdown
#> Loading required package: tidyr

set.seed(1)
dat <- data.frame(x = runif(20), y = runif(20), z = runif(20))
gp_kern <- k_Exponential(D = 2)
gp_fit <- gpkm(z ~ x + y, data = dat, kernel = gp_kern)

gp_fit$pred(dat[, 1:2])
#> Error in .subset2(x, i, exact = exact): invalid subscript type 'list'
```

<sup>Created on 2024-11-23 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I'll have a PR for this shortly...

### PR DESCRIPTION
**Pull request by topepo**
Closes #5 

More in-line comments to follow

### CODE REVIEW

File: R/convert_X_with_formula.R [hunk 1]
```diff
@@ -62,7 +62,7 @@ convert_X_with_formula <- function(X, convert_formula_data, formula) {
     convert_formula_data$chars,
     function(li) {li$index}
   )
-  for (ind in 1:length(charinds)) {
+  for (ind in seq_along(charinds)) {
```
Comment (topepo) [inline R/convert_X_with_formula.R:65]: This is the main change for the error in #5

File: R/kernel_Factor.R [hunk 2]
```diff
@@ -202,7 +202,7 @@ FactorKernel <- R6::R6Class(
       y <- y[self$xindex]
       stopifnot(x>=1, y>=1, x<=self$nlevels, y<=self$nlevels,
                 abs(x-as.integer(x)) < 1e-8, abs(y-as.integer(y)) < 1e-8)
-      if (x==y) {
```
Comment (topepo) [inline R/kernel_Factor.R:205]: This is an extra issue that I ran into. There is one other changed here but some more that I didn't touch (with `xx == yy`) because I didn't encounter triggers for them

File: tests/testthat/test_predictions.R [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+      list(mean = numeric(0), s2 = numeric(0), se = numeric(0)),
+      row.names = integer(0),
+      class = "data.frame")
+
+  expect_equal(preds[0,], exp_ptype)
+  expect_equal(nrow(preds), nrow(dat))
+
+})
+
+test_that("prediction with only categorical predictors", {
```
Comment (topepo) [inline tests/testthat/test_predictions.R:20]: I don't know if this is a feasible test case. Do you want folks to be able to fit purely categorical predictor models?

File: tests/testthat/test_predictions.R [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+      class = "data.frame")
+
+  expect_equal(preds[0,], exp_ptype)
+  expect_equal(nrow(preds), nrow(dat))
+
+})
+
+test_that("prediction with mixed predictor types", {
+  skip("Appears to cause an inf loop of warnings")
+  # This runs fine interactively but, during testing, is issues infinite
```
Comment (topepo) [inline tests/testthat/test_predictions.R:46]: Works (maybe?) but lots of warnings and a seg fault if the test code is run interactively.

**Review by CollinErickson — APPROVED** [review]
Thanks for the fix. I might change the file name for your test file but it looks good besides that.
